apiVersion: v1
data:
  name: cHJvbWV0aGV1cw==
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9wcm9tZXRoZXVzLWNvbW11bml0eS5naXRodWIuaW8vaGVsbS1jaGFydHM=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-prometheus
  namespace: argocd
type: Opaque