apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-test-infra-elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: elasticsearch
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.17.3
    chart: elasticsearch
    helm:
      valueFiles:
        - elasticsearch-values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
