apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cc-test-infra-elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: elasticsearch
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ''
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.17.3
    chart: elasticsearch
    helm:
      valueFiles:
        - values.yaml
      values: |-
        ---
        # from elasticsearch-values.yaml
        # Image specifications
        image: "docker.elastic.co/elasticsearch/elasticsearch"
        imageTag: "8.1.0"
        imagePullPolicy: "IfNotPresent"

        # Permit co-located instances for solitary minikube virtual machines.
        antiAffinity: "soft"

        # Shrink default JVM heap.
        esJavaOpts: "-Xmx450m -Xms450m"

        # Allocate smaller chunks of memory per pod.
        resources:
          requests:
            cpu: "100m"
            memory: "768M"
          limits:
            cpu: "1000m"
            memory: "768M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "local-path"
  resources:
    requests:
      storage: 1Gi
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
