apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-cc-test
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/janpastrnak/argocd
          revision: main
          directories:
          - path: resources/v-02/overlays/*
      - list:
          elements:
          - cluster: cc-test-infra
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/janpastrnak/argocd
        targetRevision: main
        path: '{{path}}/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
