apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set-overlays
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/janpastrnak/argocd
          revision: main
          directories:
          - path: resources/v-02/overlays/*
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/janpastrnak/argocd
        targetRevision: main
        path: '{{path}}/{{name}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
